name: first workflow  
on: workflow_dispatch
jobs: 
  first_job: 
    runs-on: ububtu-latest
    steps: 
      - name: saying Hello
        run: echo "Hello"
      - name: saying bye
        run: echo "Done! Bye"
